// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVdhZ5ObZYNkFSldkljM2mQOlWaxc-B0',
    appId: '1:1054726038491:web:081979c63c89d756a4fdfe',
    messagingSenderId: '1054726038491',
    projectId: 'toaqui-familia-app',
    authDomain: 'toaqui-familia-app.firebaseapp.com',
    storageBucket: 'toaqui-familia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6U5w2QDJXFwKIjYH9XJSal1l-8xM7zmA',
    appId: '1:1054726038491:android:b77bb43b2c9a84b5a4fdfe',
    messagingSenderId: '1054726038491',
    projectId: 'toaqui-familia-app',
    storageBucket: 'toaqui-familia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg0vWtya_ZCFfUHFmd-R82U-qpcNEkRA4',
    appId: '1:1054726038491:ios:93e90388085192ada4fdfe',
    messagingSenderId: '1054726038491',
    projectId: 'toaqui-familia-app',
    storageBucket: 'toaqui-familia-app.firebasestorage.app',
    iosBundleId: 'com.example.toAqui',
  );
}
